### ISSUE TITLE
libmpv_render: after creating texture: OpenGL error INVALID_ENUM

### ISSUE THREAD

**Issue by Asthestarsfalll** [kanehekili/VideoCut#40] opened 2024-07-22 03:34 UTC
When cutting video, it will raise error :
```
ERROR : Remux failed Command '['/opt/videocut/ffmpeg/bin/remux5', '-i', 'xxx', '-s', '00.000,1499.831,4979.441,12622.743', 'xxx']' returned non-zero exit status 127.
``` 
I check the log and find:
```
ERROR  :  > libmpv_render: after creating texture: OpenGL error INVALID_ENUM
```

I am using the version  3.0.2 of videocut, and pervious version works well.

**Comment by kanehekili** [comment] 2024-07-26 21:42
This seems to be two different errors. First the cut fails, then MPV gets an OPENGL error.  Could you describe which Linux you are using? Which ffmpeg version is installed? 
I could reproduce the remux error: Having ffmpg Version 7 ist needs the corresponding remux5 binary. 
I've updated the source code (not the builds, they work) with a V7 version

**Comment by Asthestarsfalll** [comment] 2024-07-27 05:18
Thank you for your reply!
I am using Manjaro linux. My ffmpeg version is `n7.0.1`.

**Comment by kanehekili** [comment] 2024-07-27 23:48
jep - just updated manjaro and videocut fails. I'll have to look into this dependency mess an will report back. Thanks for reporting. It fails on all manjaro instances. WTF

**Comment by kanehekili** [comment] 2024-07-28 19:09
I assume you've downloaded and build videocut before the upgrade of ffmpeg7 arrived. Until this upgrade it worked, then the libraries VC uses changed.
Just rebuild videocut in pamac or via "makepkg -s". Sorry for the inconvenience. If it works, close the issue

**Closed as completed** 2024-07-31 11:06 UTC
